site_name: SQLitePlus Enhanced
theme:
  name: material

nav:
  - Inicio: index.md
  - Instalación: instalacion.md
  - Uso Básico: uso_basico.md
  - Uso Avanzado: uso_avanzado.md
  - API: api.md
  - CLI: cli.md
  - Configuración: configuracion.md
  - Endpoints: endpoints.md
  - Changelog: changelog.md
  - English:
      - Home: en/index.md
      - Installation: en/installation.md
      - Basic Usage: en/basic_usage.md
      - Advanced Usage: en/advanced_usage.md
      - API: en/api.md
      - CLI: en/cli.md
      - Configuration: en/configuration.md
      - Endpoints: en/endpoints.md
      - Changelog: en/changelog.md
      - Security Audit: en/security_remediation_plan.md

